//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseSystemApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Server> ServerSet { get; set; }
        public virtual DbSet<DataBase> DataBaseSet { get; set; }
        public virtual DbSet<Table> TableSet { get; set; }
        public virtual DbSet<Column> ColumnSet { get; set; }
        public virtual DbSet<Mask> MaskSet { get; set; }
        public virtual DbSet<Type> TypeSet { get; set; }
        public virtual DbSet<Connection> ConnectionSet { get; set; }
        public virtual DbSet<SysDiagrams> SysDiagramsSet { get; set; }
    }
}
