//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ForeignKeyColumn { get; set; }
        public Nullable<int> PrimaryKeyColumn { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual Column Column1 { get; set; }
    }
}
